dependencies {
    implementation project(':hospital-common')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'com.baomidou:mybatis-plus-boot-starter:3.5.3.1'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'io.minio:minio:8.5.7'
    implementation 'com.squareup.okhttp3:okhttp:4.10.0'
    implementation 'org.apache.poi:poi:5.2.3'
    implementation 'org.apache.poi:poi-ooxml:5.2.3'
    implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity5'
    runtimeOnly 'com.mysql:mysql-connector-j'
}