plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':hospital-common')
    implementation project(':hospital-qmg')
    implementation project(':hospital-neuroimmune')
    implementation project(':hospital-ocr')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    // Knife4j API 文档（Spring Boot 3.x 版本）
    implementation 'com.github.xiaoymin:knife4j-openapi3-jakarta-spring-boot-starter:4.5.0'
    // Ensure okhttp 4.x for MinIO compatibility
    implementation 'com.squareup.okhttp3:okhttp:4.10.0'

    // 排除默认的 logback，使用 log4j2
    configurations {
        all {
            exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
        }
    }
    implementation 'org.springframework.boot:spring-boot-starter-log4j2'
}

bootJar {
    archiveFileName = 'hospital-platform.jar'
    mainClass = 'org.hospital.HospitalApplication'
}